name: Docker Image CI

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]


jobs:
    build_backend:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v4
       - name: Build the Backend Docker image
         run: docker build ./backend --file ./backend/Dockerfile --tag document-chatbot-backend:$(date +%s)


    build_frontend:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v4
       - name: Build the Frontend Docker image
         run: docker build ./frontend --file ./frontend/Dockerfile --tag document-chatbot-frontend:$(date +%s)

